Api
sleepingming/Rails pull request #17
Opened 2022-01-20 20:09 UTC by sleepingming

2022-01-21 07:15 UTC, VidgarVii requested changes

2022-01-21 07:15 UTC, VidgarVii commented on app/controllers/admin/gists_controller.rb
> +  end
для чего этот метод нужен? Он же не используется?

2022-01-21 07:15 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    result.call
лучше call сразу вызывать
`GistQuestionService.new(@test_passage.current_question).call`

в руби нет практики разделять порождение объектов и вызов методов, как например в js Тем более ради 1 метода

2022-01-21 07:15 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    url = result.gist_url
абсолютно бессмысленная операция загрязняющая память. Лучше вызывать методы там где это надо и не определять лишних переменных

2022-01-21 07:15 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    if url.present?
вот это вот часть логики которая должна лежать в сервисе и не мучать этим контроллер
Суть создания отдельного класса - вынести в него часть логики и скрыть детали реализации. Логика определения успешности создания Гиста тоже лучше оставить в сервис и не мучить дополнительной сложностью контроллер. 
Но проверять успех в контроллере конечно надо.
Для этого есть стандартный подход для контроллера при работе с любым сервисом

```ruby
result = SomeService.new(...).call

if result.success?
  ...
else
  ...
end
```
Метод call должен вернуть такой объект, который содержит все нужные методы и данные. И хорошо если всё это будет прописано в явном виде. Сейчас же не понятно от куда берутся методы такие как html_url. 
Для создания такого объекта можно воспользоваться Struct

2022-01-21 07:15 UTC, VidgarVii commented on config/locales/en.yml
> +      success: <b><a href="%{url}">Gist</a> created </b>
если локаль возвращает хтмл то принято это показывать явно
Надо переименовать ключ в success_html. Плюс отключает экранирование
http://rusrails.ru/rails-internationalization-i18n-api#ispolzovanie-html-bezopasnyh-perevodov

2022-01-21 07:15 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    end.join.html_safe
суть проверки if flash[type] сделать верстку гибкой. Чтобы можно было управлять на странице где какой тип флеша показывать

2022-01-21 07:15 UTC, VidgarVii commented on app/views/admin/_nav.html.erb
> +    <%= link_to "Выйти", destroy_user_session_path, method: :delete %>
как раз принято по умолчанию ставить одинарные ковычки. А двойные только при интерполяции

2022-01-21 07:15 UTC, VidgarVii commented on app/views/admin/gists/_gist.html.erb
> +  <td><%= link_to "#{gist.question.body[0..24]}", admin_question_path(gist.question)%></td>
здесь лучше использовать хелпер `truncate` - [вот небольшой пост про него](https://makandracards.com/makandra/53287-heads-up-rails-offers-two-similar-means-for-text-truncation)

2022-01-24 07:48 UTC, VidgarVii commented on Gemfile
> +gem 'devise', '~> 4.0'
что в этом ПР devise делает? До этого его не было?

2022-01-24 07:48 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    result = GistQuestionService.new(@test_passage.current_question).gist
не совсем понятно как метод gist стыкуется с переменной  result
наверное лучше назвать метод call
Тем более потом вызываем проверку success?

2022-01-24 07:48 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
еще можно так:
```ruby
[@question.body, *@question.answers.pluck(:body)].join("\n")
```
уменьшит потребление памяти и выглядит лучше

2022-01-24 07:48 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
установка "нил" в аргументах - это возможно не лучшее решение
я бы для такого случая порекомендовал вариант установки дефолта, к примеру, такой:
```ruby
def initialize(question, client = default_client)
  ...
  @client = client
end
```
далее можно определить в методе `default_client` "дефолтного клиента"

```ruby
private

def default_client
  Octokit::Client.new(access_token: GITHUB_GIST_TOKEN)
end
```

2022-01-28 15:41 UTC, sleepingming commented on Gemfile
> +gem 'devise', '~> 4.0'
давно не закидывал гемфайл в коммиты

2022-01-28 16:24 UTC, merged